services:
  backend:
    build: ./backend
    container_name: logiflow-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_MONGODB_HOST: mongodb
      SPRING_MONGODB_PORT: 27017
      SPRING_MONGODB_DATABASE: ${SPRING_MONGODB_DATABASE}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
      COOKIE_SECURE: ${COOKIE_SECURE}
      SUPER_ADMIN_USERNAME: ${SUPER_ADMIN_USERNAME}
      SUPER_ADMIN_EMAIL: ${SUPER_ADMIN_EMAIL}
      SUPER_ADMIN_PASSWORD: ${SUPER_ADMIN_PASSWORD}
      SUPER_ADMIN_FULL_NAME: ${SUPER_ADMIN_FULL_NAME}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - logiflow-network

  frontend:
    build: ./frontend
    container_name: logiflow-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - logiflow-network

  mongodb:
    image: mongo:latest
    container_name: logiflow-mongo
    environment:
      MONGO_INITDB_DATABASE: ${SPRING_MONGODB_DATABASE}
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - logiflow-network
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:18.1-alpine
    container_name: logiflow-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - logiflow-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.2.2-alpine
    container_name: logiflow-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - logiflow-network
    volumes:
      - redis_data:/data

networks:
  logiflow-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  redis_data: