services:
  mongodb:
    image: mongo:latest
    container_name: logiflow-mongo
    environment:
      MONGO_INITDB_DATABASE: logiflow
    ports:
      - "27017:27017"
  postgres:
    image: postgres:latest
    container_name: logiflow-postgres
    environment:
      POSTGRES_DB: logiflow
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: myuser
    ports:
      - "5432:5432"
