spring:
  application:
    name: LogiFlow
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  mongodb:
    uri: mongodb://${SPRING_MONGODB_HOST}:${SPRING_MONGODB_PORT}/${SPRING_MONGODB_DATABASE}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  cookie:
    secure: ${COOKIE_SECURE}
  super-admin:
    username: ${SUPER_ADMIN_USERNAME}
    email: ${SUPER_ADMIN_EMAIL}
    password: ${SUPER_ADMIN_PASSWORD}
    full-name: ${SUPER_ADMIN_FULL_NAME}

