spring:
  application:
    name: LogiFlow
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/logiflow}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver